// lib/questions.ts
import { DomainKey } from '@/types'

export interface Question {
  id: string
  domain: DomainKey
  question: string
  options: string[]
  correct: number
  explanation: string
}

export const QUESTIONS: Question[] = [
  // D1: Agentic Architecture (8 questions)
  {
    id: 'd1-1',
    domain: 'd1',
    question: 'Which stop_reason indicates Claude wants to invoke a tool?',
    options: ['end_turn', 'tool_use', 'max_tokens', 'stop_sequence'],
    correct: 1,
    explanation: 'stop_reason="tool_use" means Claude\'s response contains a tool_use content block. The agent must execute the tool and return a tool_result before continuing.',
  },
  {
    id: 'd1-2',
    domain: 'd1',
    question: 'In an agentic loop, after Claude returns a tool_use block, what must be appended to the messages array?',
    options: [
      'Just a user turn with the tool_result',
      'The full assistant response (with tool_use), then a user turn with tool_result',
      'A new user message restating the original request',
      'Nothing — Claude automatically continues',
    ],
    correct: 1,
    explanation: 'Both messages are required: the assistant turn (containing the tool_use block) and a user turn with type "tool_result" referencing the tool_use_id. Omitting the assistant turn causes an API error.',
  },
  {
    id: 'd1-3',
    domain: 'd1',
    question: 'What is the primary role of an orchestrator in a multi-agent system?',
    options: [
      'Execute tool calls directly',
      'Store conversation history',
      'Break tasks into subtasks, dispatch agents, and aggregate results',
      'Rate-limit API calls',
    ],
    correct: 2,
    explanation: 'The orchestrator coordinates the system — it decomposes complex tasks, delegates to specialized subagents, and synthesizes their outputs into a final result.',
  },
  {
    id: 'd1-4',
    domain: 'd1',
    question: 'A PreToolUse hook script exits with code 1. What happens in Claude Code?',
    options: [
      'The tool runs normally',
      "The tool is blocked and the hook's stdout is passed to Claude as context",
      "The tool is blocked and the hook's stdout is shown to the user",
      'Claude Code crashes',
    ],
    correct: 1,
    explanation: 'Exit code 1 (any non-zero, non-2) blocks the tool call and sends the hook stdout back to Claude as additional context, allowing Claude to adjust its approach. Exit code 2 is a blocking error that sends the hook\'s stderr to Claude as a forced error message.',
  },
  {
    id: 'd1-5',
    domain: 'd1',
    question: 'You want to resume the most recent Claude Code session. Which flag is correct?',
    options: ['claude --new', 'claude --continue', 'claude --restore', 'claude --session-id last'],
    correct: 1,
    explanation: '--continue resumes the most recent conversation. --resume <session-id> resumes a specific past session. These flags preserve context from the previous session.',
  },
  {
    id: 'd1-6',
    domain: 'd1',
    question: 'A tool returns { "error": "File not found", "path": "/tmp/data.csv" } instead of throwing an exception. How does Claude handle this?',
    options: [
      'Claude crashes with an unhandled exception',
      'Claude ignores the error and returns end_turn',
      'Claude reads the structured error and decides whether to retry, use a different approach, or report to the user',
      'The API returns a 500 error',
    ],
    correct: 2,
    explanation: 'Structured error responses allow Claude to reason about what went wrong and act on it — something impossible if the tool throws an unhandled exception.',
  },
  {
    id: 'd1-7',
    domain: 'd1',
    question: 'When should a multi-agent orchestrator dispatch subagents in parallel rather than sequentially?',
    options: [
      'Always — parallelism is always faster',
      'When subtasks are independent and do not share mutable state',
      'Only when the user explicitly requests it',
      'When subtasks have sequential dependencies on each other',
    ],
    correct: 1,
    explanation: 'Parallel dispatch works well for independent tasks (e.g., searching different data sources simultaneously). Tasks with sequential dependencies must run in order.',
  },
  {
    id: 'd1-8',
    domain: 'd1',
    question: 'What is the recommended max_tokens setting for agentic tasks with multiple sequential tool calls?',
    options: [
      '256 (minimum to save cost)',
      '1024',
      '4096 or higher — enough for multi-step reasoning and tool responses',
      'max_tokens does not apply to agentic tasks',
    ],
    correct: 2,
    explanation: 'Agentic tasks involve multi-step reasoning. A low max_tokens will cause stop_reason="max_tokens" mid-task, cutting off the response. Set 4096+ for agentic workflows.',
  },
  {
    id: 'd1-9',
    domain: 'd1',
    question: 'You configure a custom sub-agent with permissionMode: bypassPermissions. What is the effect?',
    options: [
      'The sub-agent cannot use any tools without user approval',
      'The sub-agent runs in read-only mode',
      'The sub-agent inherits the parent session\'s permission mode',
      'The sub-agent skips all permission prompts and can execute operations without approval',
    ],
    correct: 3,
    explanation: 'bypassPermissions skips permission prompts, allowing the sub-agent to execute operations without approval. Note: writes to .git, .claude, .vscode, and .idea still prompt for confirmation. Use with caution.',
  },
  {
    id: 'd1-10',
    domain: 'd1',
    question: 'You need multiple Claude Code agents to actively debate competing hypotheses and challenge each other\'s findings. Which architecture should you use?',
    options: [
      'Multiple sub-agents reporting results back to an orchestrator',
      'Agent teams with a shared task list and direct inter-agent messaging',
      'A single agent with extended thinking enabled',
      'Parallel /batch units in isolated worktrees',
    ],
    correct: 1,
    explanation: 'Agent teams allow teammates to send messages directly to each other (not just report back to the lead), share a task list, and coordinate autonomously. This is necessary for debate-style workflows where agents challenge each other\'s conclusions.',
  },
  {
    id: 'd1-11',
    domain: 'd1',
    question: 'What does isolation: worktree in a custom sub-agent\'s frontmatter do?',
    options: [
      'Runs the sub-agent in a temporary git worktree, giving it an isolated copy of the repository',
      'Prevents the sub-agent from accessing the internet',
      'Restricts the sub-agent to read-only operations',
      'Isolates the sub-agent\'s context from the main conversation',
    ],
    correct: 0,
    explanation: 'isolation: worktree creates a temporary git worktree for the sub-agent to work in. This prevents conflicts when multiple agents edit the same files. The worktree is automatically cleaned up if the sub-agent makes no changes.',
  },
  {
    id: 'd1-12',
    domain: 'd1',
    question: 'Which built-in Claude Code sub-agent uses the Haiku model and is optimized for read-only codebase search?',
    options: [
      'Plan',
      'general-purpose',
      'Explore',
      'Bash',
    ],
    correct: 2,
    explanation: 'The Explore sub-agent uses the Haiku model (fast, low-latency) and has read-only tools. It\'s automatically used for file discovery and codebase exploration. Using Haiku keeps costs low for read-heavy research work.',
  },
  {
    id: 'd1-13',
    domain: 'd1',
    question: 'In addition to the command type, which other hook implementation types does Claude Code support?',
    options: [
      'file, url, and script',
      'async, sync, and blocking',
      'webhook, eval, and subagent',
      'http, prompt, and agent',
    ],
    correct: 3,
    explanation: 'Claude Code supports four hook implementation types: command (shell command), http (POST to an endpoint), prompt (send a prompt to Claude for evaluation), and agent (spawn a sub-agent for verification).',
  },
  {
    id: 'd1-14',
    domain: 'd1',
    question: 'You want to enforce that every task marked as complete in an agent team must pass your test suite. Which hook event and exit code should you use?',
    options: [
      'TeammateIdle with exit 2',
      'TaskCompleted with exit 2',
      'SubagentStop with exit 1',
      'PostToolUse with exit 0',
    ],
    correct: 1,
    explanation: 'TaskCompleted fires when a task is being marked complete. Exiting with code 2 blocks the completion and sends your stderr message as feedback to the agent, forcing it to fix the issue before the task can be marked done.',
  },
  {
    id: 'd1-15',
    domain: 'd1',
    question: 'The skills field in a custom sub-agent\'s frontmatter preloads skills differently than how they load in normal sessions. What is the key difference?',
    options: [
      'Skills in the skills field load only the description, not the full content',
      'Skills in the skills field are read-only and cannot be invoked with slash commands',
      'Skills in the skills field inject the full skill content at startup, not just make it available for invocation',
      'Skills in the skills field override the sub-agent\'s system prompt',
    ],
    correct: 2,
    explanation: 'In normal sessions, skill descriptions are loaded into context but full content only loads on invocation. When a sub-agent has skills in its frontmatter, the FULL skill content is injected at startup. Sub-agents don\'t inherit skills from the parent conversation — you must list them explicitly.',
  },

  // D2: Tool Design & MCP (6 questions)
  {
    id: 'd2-1',
    domain: 'd2',
    question: 'What is the recommended naming convention for Claude tool names?',
    options: ['PascalCase (SearchWeb)', 'camelCase (searchWeb)', 'snake_case (search_web)', 'UPPER_CASE (SEARCH_WEB)'],
    correct: 2,
    explanation: 'Tool names should use snake_case with a verb-noun pattern (e.g., search_web, read_file). This follows Anthropic tool design guidelines and is the most readable format for Claude.',
  },
  {
    id: 'd2-2',
    domain: 'd2',
    question: 'A file-reading tool fails because the file does not exist. What should it return?',
    options: [
      'null',
      'An empty string ""',
      'throw new Error("File not found")',
      '{ "error": "File not found", "path": "/requested/file.txt" }',
    ],
    correct: 3,
    explanation: 'Tools should return structured errors, not throw exceptions or return null. A structured error gives Claude actionable information to decide its next step.',
  },
  {
    id: 'd2-3',
    domain: 'd2',
    question: 'How do you force Claude to use a specific tool named "extract_data"?',
    options: [
      'tool_choice: { type: "auto" }',
      'tool_choice: { type: "any" }',
      'tool_choice: { type: "tool", name: "extract_data" }',
      'Set that tool first in the tools array',
    ],
    correct: 2,
    explanation: 'tool_choice: { type: "tool", name: "..." } forces Claude to use that specific tool. This is essential for structured output patterns.',
  },
  {
    id: 'd2-4',
    domain: 'd2',
    question: 'What is the key difference between stdio and SSE MCP transports?',
    options: [
      'stdio supports more tools; SSE is limited to 10',
      'stdio runs a local subprocess (secure); SSE connects to a remote HTTP server',
      'SSE is for Claude Code only; stdio is for the API',
      'They are identical in behavior',
    ],
    correct: 1,
    explanation: 'stdio spawns a local subprocess connected via stdin/stdout — simpler, more secure for local tools. SSE connects to a remote server over HTTP, useful for shared team infrastructure.',
  },
  {
    id: 'd2-5',
    domain: 'd2',
    question: 'You want to search file contents for a regex pattern. Which built-in Claude Code tool should you prefer?',
    options: ['Bash (grep command)', 'Grep', 'WebSearch', 'Read'],
    correct: 1,
    explanation: 'The Grep tool is the correct choice. It\'s faster and safer than running grep via Bash, and provides structured output. Reserve Bash for operations where no dedicated tool exists.',
  },
  {
    id: 'd2-6',
    domain: 'd2',
    question: 'An agent needs to read files and search the web, but must NOT execute shell commands. What principle guides its tool configuration?',
    options: [
      'Expose all tools so Claude can choose the best one',
      'Principle of least privilege — only expose the tools the agent actually needs',
      'Always expose Bash for fallback flexibility',
      'Use the Computer tool as a universal replacement',
    ],
    correct: 1,
    explanation: 'Agents should only have access to the tools they need for their task. Exposing unnecessary tools (especially Bash) increases blast radius and security risk.',
  },

  // D3: Claude Code Configuration (15 questions)
  {
    id: 'd3-1',
    domain: 'd3',
    question: 'In what order does Claude Code apply CLAUDE.md files when multiple levels exist?',
    options: [
      'Subdirectory → project root → global (most specific wins on conflict)',
      'Global → project root → subdirectory (most specific overwrites)',
      'Only the project root CLAUDE.md is loaded',
      'The last CLAUDE.md found in the directory tree wins',
    ],
    correct: 0,
    explanation: 'All three levels are loaded and merged. More specific files (subdirectory) take precedence over general ones (global) on conflicts. All levels are additive — not mutually exclusive.',
  },
  {
    id: 'd3-2',
    domain: 'd3',
    question: 'Where should a custom /review slash command be placed to use it in ALL projects?',
    options: [
      '<project>/.claude/commands/review.md',
      '~/.claude/commands/review.md',
      '~/.claude/skills/review.md',
      '<project>/CLAUDE.md',
    ],
    correct: 1,
    explanation: 'Global commands go in ~/.claude/commands/. Project-scoped commands go in <project>/.claude/commands/. Global placement makes the command available in all projects.',
  },
  {
    id: 'd3-3',
    domain: 'd3',
    question: 'How do you enter plan mode in Claude Code?',
    options: ['Type /plan in chat', 'Press Shift+Tab', 'Run claude --plan', 'Invoke the ExitPlanMode tool'],
    correct: 1,
    explanation: 'Shift+Tab toggles plan mode. In plan mode, Claude explores the codebase but does not write code until the user approves the plan via the ExitPlanMode tool.',
  },
  {
    id: 'd3-4',
    domain: 'd3',
    question: 'What does the ExitPlanMode tool do when Claude invokes it?',
    options: [
      'Terminates the Claude Code session',
      'Signals that planning is complete and presents the plan to the user for approval',
      'Switches Claude to read-only mode permanently',
      'Exports the plan to a markdown file automatically',
    ],
    correct: 1,
    explanation: 'ExitPlanMode signals plan completion. The user sees the plan and can approve (Claude proceeds) or request changes. It is the handoff between planning and execution.',
  },
  {
    id: 'd3-5',
    domain: 'd3',
    question: 'You are building a CI pipeline that runs Claude to auto-generate PR descriptions. Which flag must you use?',
    options: ['--verbose', '--headless', '--interactive', '--safe'],
    correct: 1,
    explanation: '--headless makes Claude Code fully non-interactive, disabling all confirmation prompts. This is required for automated CI pipelines where there is no human to approve prompts.',
  },
  {
    id: 'd3-6',
    domain: 'd3',
    question: 'What is the key difference between a Claude Code command and a skill?',
    options: [
      'Commands run in the terminal; skills run in the browser',
      'Commands are explicit /name invocations; skills have trigger descriptions and can be invoked proactively',
      'Skills support TypeScript; commands are markdown only',
      'There is no difference — they are synonyms',
    ],
    correct: 1,
    explanation: 'Commands (/name) are always explicitly invoked by the user. Skills have description fields Claude uses to decide when to trigger them proactively via the Skill tool.',
  },
  {
    id: 'd3-7',
    domain: 'd3',
    question: 'Why should you put project context in CLAUDE.md rather than explaining it in the first chat message?',
    options: [
      'CLAUDE.md is parsed faster than chat messages',
      'CLAUDE.md is injected at the start of every session — Claude always has context without the user re-explaining it',
      'Chat messages are not visible to Claude',
      'CLAUDE.md supports formatting that chat messages do not',
    ],
    correct: 1,
    explanation: 'Claude does not remember previous conversations. CLAUDE.md is automatically injected at session start, ensuring consistent project context across all sessions without repetition.',
  },
  {
    id: 'd3-8',
    domain: 'd3',
    question: 'You want to prevent Claude from ever automatically triggering your /deploy skill without explicit user invocation. Which frontmatter setting achieves this?',
    options: [
      'Set user-invocable: false',
      'Set disable-model-invocation: true',
      'Set context: fork',
      'Omit the description field',
    ],
    correct: 1,
    explanation: 'disable-model-invocation: true removes the skill from Claude\'s context entirely, so Claude never auto-invokes it. The user still triggers it with /deploy. user-invocable: false is the opposite — it hides the skill from the user but lets Claude invoke it.',
  },
  {
    id: 'd3-9',
    domain: 'd3',
    question: 'A skill has context: fork in its frontmatter. What does this mean?',
    options: [
      'The skill runs in an isolated subagent context without access to the main conversation history',
      'The skill creates a git fork before running',
      'The skill can only be invoked in forked repositories',
      'The skill runs with elevated permissions',
    ],
    correct: 0,
    explanation: 'context: fork runs the skill as a subagent in its own isolated context. The skill content becomes the subagent\'s task prompt. The subagent does NOT have access to the main conversation history — it starts fresh.',
  },
  {
    id: 'd3-10',
    domain: 'd3',
    question: 'What does the backtick-bang syntax (!`command`) do inside a SKILL.md file?',
    options: [
      'Asks Claude to run the command during skill execution',
      'Creates a shell alias for the command',
      'Runs the command at preprocessing time and injects the output into the skill prompt before Claude sees it',
      'Validates that the command is safe to run',
    ],
    correct: 2,
    explanation: 'The !`command` syntax in SKILL.md is preprocessing — it runs the command BEFORE Claude receives the skill content, and the output replaces the placeholder inline. Claude sees the actual data, not the command string.',
  },
  {
    id: 'd3-11',
    domain: 'd3',
    question: 'You have 30 independent source files that each need the same migration applied. Which Claude Code feature is specifically designed for this type of large-scale parallel change?',
    options: [
      'Agent teams',
      'The /batch skill',
      'Multiple --worktree flags',
      'A PreToolUse hook',
    ],
    correct: 1,
    explanation: 'The /batch skill is purpose-built for this. It decomposes the work into independent units, spawns one background agent per unit in an isolated git worktree, has each agent run tests, and opens a PR per unit. Agent teams require manual coordination; /batch automates the decomposition.',
  },
  {
    id: 'd3-12',
    domain: 'd3',
    question: 'A .claude/rules/testing.md file has paths: ["**/*.test.ts"] in its frontmatter. When does this rule load into context?',
    options: [
      'Never — path-scoped rules must be imported manually',
      'At session start, like CLAUDE.md',
      'Only when the user types /testing',
      'Only when Claude is working with files matching **/*.test.ts',
    ],
    correct: 3,
    explanation: 'Path-scoped rules in .claude/rules/ only load into context when Claude reads files matching the specified patterns. This keeps context lean — test-specific rules don\'t consume tokens during non-test work.',
  },
  {
    id: 'd3-13',
    domain: 'd3',
    question: 'What is the key difference between CLAUDE.md and Claude Code auto memory?',
    options: [
      'CLAUDE.md is temporary; auto memory persists across sessions',
      'CLAUDE.md is written by you; auto memory is written by Claude based on what it learns',
      'CLAUDE.md loads on demand; auto memory loads at every session start',
      'CLAUDE.md is project-scoped; auto memory is global',
    ],
    correct: 1,
    explanation: 'CLAUDE.md contains instructions you write for Claude. Auto memory is Claude writing notes for itself — build commands it discovered, debugging patterns, architecture decisions it learned. Both load at session start, but CLAUDE.md is user-authored while auto memory is Claude-authored.',
  },
  {
    id: 'd3-14',
    domain: 'd3',
    question: 'You want a Claude Code task to run nightly to review open PRs, even when your laptop is off. Which scheduling option should you use?',
    options: [
      '/loop inside a CLI session',
      'Desktop scheduled tasks',
      'Cloud scheduled tasks',
      'A PreToolUse hook on SessionStart',
    ],
    correct: 2,
    explanation: 'Cloud scheduled tasks run on Anthropic-managed infrastructure, so they persist even when your machine is off. Desktop scheduled tasks require your machine to be running. /loop only runs while a session is open.',
  },
  {
    id: 'd3-15',
    domain: 'd3',
    question: 'Which built-in bundled skill spawns parallel agents in isolated git worktrees and opens one pull request per unit of work?',
    options: [
      '/simplify',
      '/loop',
      '/batch',
      '/debug',
    ],
    correct: 2,
    explanation: '/batch decomposes a large-scale task into 5–30 independent units and spawns one background agent per unit in an isolated git worktree. Each agent implements its unit, runs tests, and opens a pull request.',
  },

  // D4: Prompt Engineering (7 questions)
  {
    id: 'd4-1',
    domain: 'd4',
    question: 'What is the main advantage of using tool_choice to force structured output vs. asking Claude to "respond with JSON"?',
    options: [
      'tool_choice is significantly faster',
      'Asking for JSON is more flexible',
      'tool_choice guarantees valid JSON matching the defined schema; asking for JSON in text can produce markdown fences or narrative',
      'tool_choice is only available in Claude 3+',
    ],
    correct: 2,
    explanation: "When you force a tool call via tool_choice, Claude must populate the tool's parameters according to the schema. The result is always valid parseable JSON — no markdown fences, no extra text.",
  },
  {
    id: 'd4-2',
    domain: 'd4',
    question: 'When using few-shot examples in a prompt, where should they be placed?',
    options: [
      'Before the system instructions',
      'After instructions but before the actual user input',
      'At the very end, after the user input',
      'Position does not matter for few-shot examples',
    ],
    correct: 1,
    explanation: 'Standard placement: system/instructions → examples → actual task. Claude sees the format pattern just before the task it needs to apply it to, maximizing the few-shot effect.',
  },
  {
    id: 'd4-3',
    domain: 'd4',
    question: 'Which XML tags are most commonly used to structure Claude prompts?',
    options: [
      '<input>, <response>, <meta>',
      '<context>, <instructions>, <examples>, <output_format>',
      '<system>, <user>, <assistant>',
      'Claude ignores XML tags',
    ],
    correct: 1,
    explanation: 'Claude is trained to attend to structured markup. Common effective tags: <context> (background), <instructions> (task), <examples> (few-shot), <output_format> (desired format).',
  },
  {
    id: 'd4-4',
    domain: 'd4',
    question: 'In a validation-retry loop, what is the recommended maximum number of retries before escalating to a human?',
    options: ['1', '3', '10', 'Unlimited — keep retrying until success'],
    correct: 1,
    explanation: '3 retries is the recommended ceiling. After 3 failed attempts, the issue is likely structural and requires human intervention rather than more automated retries.',
  },
  {
    id: 'd4-5',
    domain: 'd4',
    question: 'Chain-of-thought prompting ("think step by step") is most effective for which type of task?',
    options: [
      'Simple factual lookups',
      'Code formatting and style fixes',
      'Multi-step reasoning tasks — math, logic, planning, complex analysis',
      'Generating short creative text snippets',
    ],
    correct: 2,
    explanation: 'Chain-of-thought dramatically improves multi-step reasoning performance. For simple or creative tasks, it adds unnecessary tokens without proportional benefit.',
  },
  {
    id: 'd4-6',
    domain: 'd4',
    question: "What should an effective retry prompt include when Claude's first response fails validation?",
    options: [
      'The full original prompt repeated verbatim',
      'Just "please try again"',
      'The original output + a specific description of what was wrong + instruction to fix exactly that',
      'A completely different prompt from scratch',
    ],
    correct: 2,
    explanation: "Effective retry prompts reference the problematic output, explain precisely what's wrong, and ask Claude to fix specifically that. This preserves context and provides actionable feedback.",
  },
  {
    id: 'd4-7',
    domain: 'd4',
    question: 'You need Claude to always extract exactly three fields (name, email, phone) from freeform user text. What is the most reliable approach?',
    options: [
      'Ask Claude to "return JSON with name, email, and phone"',
      'Define a tool with required parameters name, email, phone and use tool_choice: { type: "tool" }',
      'Use few-shot examples showing the extraction pattern',
      'Ask Claude to format output as a markdown table',
    ],
    correct: 1,
    explanation: 'Defining a tool with required parameters and forcing its use guarantees all three fields are present. The schema enforces structure at the API level, unlike free-form instructions.',
  },

  // D5: Context Management (7 questions)
  {
    id: 'd5-1',
    domain: 'd5',
    question: 'Where should stable, high-importance context (instructions, constraints) be positioned?',
    options: [
      'At the end, just before the user request',
      'At the beginning of the context (system prompt)',
      'In the middle of the conversation history',
      "Position has no effect on Claude's attention",
    ],
    correct: 1,
    explanation: 'Claude gives more weight to content at the beginning (system prompt) and end (recent turns). Stable important context belongs at the top; the specific task should come just before the assistant turn.',
  },
  {
    id: 'd5-2',
    domain: 'd5',
    question: 'Which symptom most clearly indicates context degradation in a long Claude Code session?',
    options: [
      'Claude Code runs noticeably slower',
      'API response times increase significantly',
      'Claude starts ignoring earlier instructions or making mistakes it did not make at the session start',
      'Tool calls begin to silently fail',
    ],
    correct: 2,
    explanation: 'Context degradation manifests as behavioral inconsistency — forgetting constraints, repeating earlier mistakes, or declining output quality. This indicates earlier content is getting less attention as context fills.',
  },
  {
    id: 'd5-3',
    domain: 'd5',
    question: 'A subagent encounters a database timeout it cannot recover from. What is the correct action?',
    options: [
      'Retry the operation indefinitely until it succeeds',
      'Return a success response with empty data',
      'Return a structured error to the orchestrator indicating escalation is needed',
      'Terminate the entire agent session',
    ],
    correct: 2,
    explanation: 'Subagents should propagate errors up the chain with enough context for the orchestrator to decide next steps. Silent failures or empty success responses hide problems from the system.',
  },
  {
    id: 'd5-4',
    domain: 'd5',
    question: 'Your Claude Code session is approaching the context window limit mid-task. What is the best action?',
    options: [
      'Start a brand new session and re-explain everything from scratch',
      'Run /compact to summarize and compress conversation history',
      'Increase max_tokens in the settings',
      'Delete old files to reduce context',
    ],
    correct: 1,
    explanation: '/compact triggers context compression — Claude summarizes the conversation history into a compact form, freeing context window space while preserving key decisions and state.',
  },
  {
    id: 'd5-5',
    domain: 'd5',
    question: 'Which Claude Code tool allows Claude to explicitly pause and ask the user a clarifying question?',
    options: ['UserPrompt', 'AskUserQuestion', 'RequestConfirmation', 'PauseAndAsk'],
    correct: 1,
    explanation: 'AskUserQuestion is the correct tool for pausing to ask the user something. This is preferred over making assumptions or hallucinating answers to unclear requirements.',
  },
  {
    id: 'd5-6',
    domain: 'd5',
    question: 'Before which type of operation should human-in-the-loop checkpoints always be configured?',
    options: [
      'Reading files',
      'Searching the web',
      'Irreversible operations — deleting data, deploying to production, sending emails',
      'Running unit tests',
    ],
    correct: 2,
    explanation: 'Checkpoints are critical before irreversible operations where a mistake cannot be undone. File reads, web searches, and test runs are low-risk, reversible operations.',
  },
  {
    id: 'd5-7',
    domain: 'd5',
    question: 'What does "information provenance" mean in the context of Claude-generated outputs?',
    options: [
      'The model version that generated the output',
      'The speed at which Claude generated the response',
      'Tracking and attributing which source information was used to reach each conclusion',
      'The number of tool calls made during generation',
    ],
    correct: 2,
    explanation: "Provenance means knowing the origin of information in Claude's outputs. For high-stakes applications, Claude should cite sources — enabling humans to verify the reasoning chain.",
  },
]

export function getQuestionsByDomain(domain: DomainKey | 'all'): Question[] {
  if (domain === 'all') return QUESTIONS
  return QUESTIONS.filter((q) => q.domain === domain)
}
